<?php
/**
 * Google Tag Manager Template
 *
 * @category    CVM
 * @package     CVM_GoogleTagManager
 * @author      Chris Martin <chris@chris-martin.net>
 * @copyright   Copyright (c) 2013 Chris Martin
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License 3.0 (OSL-3.0)
 */
?>
<!-- Google Tag Manager -->
<?php
// Render the data layer.
echo $this->_getDataLayer();

// Render the container snippet.
echo $this->_getContainerSnippet();
?>
<!-- End Google Tag Manager -->
